# Generated by Django 3.2.8 on 2021-10-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_alter_news_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='score',
        ),
    ]
