# Generated by Django 3.2.8 on 2021-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0004_remove_news_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
