# Generated by Django 3.2.8 on 2021-10-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0005_news_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
