# Generated by Django 3.2.8 on 2021-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0006_alter_news_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
